name: DevSecOps Pipeline (Cloud)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  packages: write

jobs:

  # 1. Tests unitaires + couverture
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - run: npm test

      - name: Sauvegarder la couverture
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  # 2. SonarQube Cloud (SAST & qualite du code)
  sonar-check:
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Recuperer la couverture
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Analyse SonarQube Cloud
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # 3. Trivy - scan des dependances (SCA)
  dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Scan du systeme de fichiers
        uses: aquasecurity/trivy-action@0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

  # 4. Build + Push image GHCR
  build-image:
    needs: [ sonar-check, dependency-scan ]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/webapp:${{ github.sha }} .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/webapp:${{ github.sha }}

  # 5. Trivy - scan de l'image (conteneur)
  container-scan:
    needs: build-image
    runs-on: ubuntu-latest

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image depuis GHCR
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/webapp:${{ github.sha }}

      - name: Scan de l'image
        uses: aquasecurity/trivy-action@0.36.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/webapp:${{ github.sha }}'
          severity: 'CRITICAL'
          exit-code: '1'
